### ISSUE TITLE
Add More Images and Visuals

### ISSUE THREAD

**Issue by ruidazeng** [DuoAlly/DuoAlly.github.io#11]
We need to incorporate more images and visuals throughout the platform to enhance user engagement and improve overall aesthetics.  

Action items:  
1. Identify areas where visuals can be added or improved.  
2. Source or create high-quality images and graphics.  
3. Implement the visuals while maintaining a consistent style and branding.  

Let’s discuss the best approach to achieve this.

**Comment by ruidazeng** [comment]
Need an image for software engineering job opening  @DuoAlly-AI-Recruiter

**Comment by DuoAlly-AI-Recruiter** [comment]
> Need an image for software engineering job opening @DuoAlly-AI-Recruiter

Done! Fixed by #27

**Comment by WHeightsAI** [comment]
Not fully fixed, still need more images.

**Comment by DanielaP0nce** [comment]
more visuals added
