### ISSUE TITLE
Update Terminology: Replace "Companions" with "Duos" or "Allies" 

### ISSUE THREAD

**Issue by ruidazeng** [DuoAlly/DuoAlly.github.io#15]
### Description:
Currently, the term "companions" is used throughout the project and documentation (e.g., "AI-powered companions"). To align better with the branding of DuoAllyAI and create a stronger connection with the themes of "duos" and "allies," I suggest replacing "companions" with "duos" or "allies."  

The name DuoAlly emphasizes the concepts of partnership, collaboration, and being an ally. Using "duos" or "allies" reinforces this identity and helps create a more cohesive brand message, and evoke a stronger sense of teamwork and camaraderie compared to "companions," which can feel passive or generic. This shift better represents the active role of the AI in supporting players.  

### Proposed Updates:  
- Replace all instances of "companions" in the documentation, marketing materials, and GitHub pages, READMEs, and ALL codebase with "duos" or "allies," depending on context.  
- Review the branding guidelines to ensure future consistency with this terminology.

**Comment by WHeightsAI** [comment]
Fixed by #16

**Comment by ruidazeng** [comment]
This is mostly fixed by #16 in this repo. In the future, we should use consistent wordings across ALL of the organization's repos and products as well.

**Comment by WHeightsAI** [comment]
> This is mostly fixed by #16 in this repo. In the future, we should use consistent wordings across ALL of the organization's repos and products as well.

We need to compile a list of repo and add it to the backlogs.
