### ISSUE TITLE
Job Applications for DuoAlly

### ISSUE THREAD

**Issue by ruidazeng** [DuoAlly/DuoAlly.github.io#17]
We need a **job application form** tailored for web developers or software engineers to join DuoAlly AI on the website (`careers.html` page would be best). This form will help us streamline the process of collecting information from potential volunteers who are interested in contributing to our project.  

#### Requirements  
- Use either **Greenhouse.io**, **Google Forms**, or any other free and accessible tool to create the form.  
- Include the following fields:  
  - Name (or Nickname)
  - Email Address  
  - GitHub Profile or Portfolio (Personal Website)
  - Resume/CV
  - Cover letter (optional).

**Comment by ruidazeng** [comment]
Duplicating Issue with #13 with no more details

**Comment by ruidazeng** [comment]
@HeXavi8 Can you add Software Engineering position too?

**Comment by ruidazeng** [comment]
@DuoAlly-AI-Recruiter Can you make the Google form for both positions?

**Comment by DuoAlly-AI-Recruiter** [comment]
Will do. Will make a pull request for the two Google forms.

> @DuoAlly-AI-Recruiter Can you make the Google form for both positions?

**Comment by WHeightsAI** [comment]
I will not be working on this page.

**Comment by DuoAlly-AI-Recruiter** [comment]
I am going to simplify this form. Not a big fan of too much extra information.

**Comment by ruidazeng** [comment]
Let's try to wrap up both this and #8 before Christmas

**Comment by DuoAlly-AI-Recruiter** [comment]
I have made the forms using Google Forms.

Will integrate them into the HTML code.

**Comment by DuoAlly-AI-Recruiter** [comment]
Application Forms:
-------------

Software Engineer: https://docs.google.com/forms/d/e/1FAIpQLSfa_EH2qlo-MAwl3q4TfjIBePc8UZ2n1L6qlcInEMHs71FYCQ/viewform?usp=header

Web Developer: https://docs.google.com/forms/d/e/1FAIpQLSd2_JaxT4yqBfda3uJLOgca8bgQC-NuLb5EwDxAr0RCkIC1-g/viewform?usp=header

**Comment by DuoAlly-AI-Recruiter** [comment]
I have integrated the forms into the html elements: #26

**Comment by DuoAlly-AI-Recruiter** [comment]
#28

**Comment by WHeightsAI** [comment]
Closed since #28 is completed.
