### ISSUE TITLE
We need an UI/UX designer

### ISSUE THREAD

**Issue by WHeightsAI** [DuoAlly/DuoAlly.github.io#28]
Can we open another position for this?

@DuoAlly-AI-Recruiter

**Comment by DuoAlly-AI-Recruiter** [comment]
Working on adding another opening.

**Comment by DuoAlly-AI-Recruiter** [comment]
Form made
------
UI/UX Designer: https://docs.google.com/forms/d/e/1FAIpQLSf6A74nRZC-J0DsZ0DHrAkBNE87W3OnyiG7UUJ8pYnbO1AFqw/viewform?usp=header

**Comment by DuoAlly-AI-Recruiter** [comment]
Fixed by #29
