### ISSUE TITLE
[Feature Request] Need to finish the "Careers" page

### ISSUE THREAD

**Issue by ruidazeng** [DuoAlly/DuoAlly.github.io#8]
Add open positions and how to apply

**Comment by ruidazeng** [comment]
Partially implemented by #18

**Comment by ruidazeng** [comment]
@HeXavi8 Can you add open position for Software Engineer and also add some emphasis, maybe a “WE ARE HIRING!!!” banner.

**Comment by WHeightsAI** [comment]
@DuoAlly-AI-Recruiter please work on this too

**Comment by ruidazeng** [comment]
Let's try to wrap up both this and #17 before Christmas

**Comment by DuoAlly-AI-Recruiter** [comment]
What is our plan with the actual description? I think we need to resort to more generic descriptions

**Comment by ruidazeng** [comment]
> @HeXavi8 Can you add open position for Software Engineer and also add some emphasis, maybe a “WE ARE HIRING!!!” banner.

This is fixed by @DuoAlly-AI-Recruiter

**Comment by ruidazeng** [comment]
We need to make the open position more obvious. Right now web users will have to scroll down to the bottom to get to the open positions and "apply" bottoms. @DuoAlly-AI-Recruiter @HeXavi8

**Comment by WHeightsAI** [comment]
I got this done!
