### ISSUE TITLE
Improve User Communication Channels

### ISSUE THREAD

**Issue by ruidazeng** [DuoAlly/DuoAlly.github.io#9]
We need to re-evaluate the current `contact.html` page and come up with a systematic approach to enable users to contact us effectively. Possible options include:  
1. Setting up a Discord server  
2. Adding a contact form on the website  
3. Providing a dedicated support email  

Let’s evaluate these options and decide on the best approach.

**Comment by ruidazeng** [comment]
Also what do we think about a chatbot?

**Comment by ruidazeng** [comment]
@DanielaP0nce Please set up a contact us page as needed. Reference `formspree.io` they have free service usually. Use the company email as the receiving end point if you can.

**Comment by DuoAlly-AI-Recruiter** [comment]
Partially implemented contact page
